name: replicate_kenny_analysis
channels:
- defaults
- conda-forge
- edeno
dependencies:
- "python>=3.6"
- loren_frank_data_processing
- replay_trajectory_classification
- replay_identification
- spectral_connectivity
- ripple_detection
- spindle_detector
- numpy
- numba
- scipy
- scikit-learn
- matplotlib
- dask
- tqdm
- ipywidgets
- jupyter
- jupyterlab
- nb_conda
- setuptools
- pytest
- nodejs
- pytest-cov
- coveralls
- holoviews
- bokeh
- pip
- pip:
  - nb_black
